name: jupyterlab-omnisci
channels:
  - conda-forge
dependencies:
  - python
  - jupyterlab
  - altair
  - pyyaml
  - mypy
  - pip:
    - vdom
    - vega_datasets
    - pymapd
    - https://github.com/ibis-project/ibis/archive/master.zip
