name: jupyterlab-omnisci
channels:
  - conda-forge
dependencies:
  - python=3.6
  - jupyterlab=0.35.3
  - altair
  - black
  - pyyaml
  - mypy
  - pylint
  - flake8
  - pip:
    - vdom
    - vega_datasets