name: jupyterlab-omnisci
channels:
  - conda-forge
dependencies:
  - python
  - jupyterlab
  - altair
  - pyyaml
  - mypy
  - pip:
    - vdom
    - vega_datasets
    - pymapd
    - git+https://github.com/ibis-project/ibis.git
