name: jupyterlab-omnisci
channels:
  - conda-forge
dependencies:
  - python=3.6
  - jupyterlab=0.35.4
  - altair
  - pyyaml
  - mypy
  - pymapd
  - pip:
    - vdom
    - vega_datasets
    - https://github.com/ibis-project/ibis/archive/master.zip
    - ipywidgets