#!/bin/bash
set -o errexit
set -o xtrace

pip install -e .
jlpm install
jlpm run build
jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build
jupyter labextension install jupyterlab-server-proxy-saulshanabrook --no-build
jupyter labextension install . --no-build
jupyter lab build


# Install jaeger-all-in-one since it isn't on conda yet
mkdir -p ~/.local/bin
wget https://github.com/jaegertracing/jaeger/releases/download/v1.14.0/jaeger-1.14.0-linux-amd64.tar.gz
tar -xvzf jaeger-1.14.0-linux-amd64.tar.gz 
chmod +x jaeger-1.14.0-linux-amd64/*
ln -s ~/.local/bin/jaeger-all-in-one jaeger-1.14.0-linux-amd64/jaeger-all-on-one