name: Run tests on example notebooks

on:
  # This avoids having duplicate builds for a pull request
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 45

    env:
      CI: "true"

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v1

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ibis-vega-transform
          environment-file: binder/environment.yml

      - name: List Conda packages
        run: conda list

      - name: Install Ibis Vega Transform extension
        run: pip install -e .

      - name: Test example notebooks
        run: xvfb-run --auto-servernum jlpm test

      - name: Upload generated images
        uses: actions/upload-artifact@v1
        with:
          name: generated-images
          path: /home/runner/work/ibis-vega-transform/images/

      - name: Upload original images
        uses: actions/upload-artifact@v1
        with:
          name: orignal-images
          path: /home/runner/work/ibis-vega-transform/ibis-vega-transform/images/
