name: Run tests on example notebooks

on:
  # This avoids having duplicate builds for a pull request
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: "true"
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - name: Setup conda
        uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: ibis-vega-transform
          environment-file: binder/environment.yml
      - name: List Conda packages
        shell: bash -l {0}
        run: conda list
      - name: Install Ibis Vega Transform extension
        shell: bash -l {0}
        run: |
          pip install -e ".[dev]"
          jlpm
          jupyter labextension install . --no-build
          jupyter lab build
      - name: Test example notebooks
        shell: bash -l {0}
        run: xvfb-run --auto-servernum npm test
      - name: Upload generated images
        uses: actions/upload-artifact@v1
        with:
          name: generated-images
          path: /home/runner/work/ibis-vega-transform/images/
      - name: Upload original images
        uses: actions/upload-artifact@v1
        with:
          name: orignal-images
          path: /home/runner/work/ibis-vega-transform/ibis-vega-transform/images/
